### ISSUE TITLE
db:migrate and db:seed errors when installing.

### ISSUE THREAD

**Issue by mhaagens** [RailsApps/rails3-bootstrap-devise-cancan#27] opened 2013-01-27 01:22 UTC
When I try to run rake db:migrate or rake db:seed during installation I get an error message saying "rake aborted! Factory already registered: user".

Can anyone help me with this?

**Comment by mhaagens** [comment] 2013-01-27 01:25
![rails_errors](https://f.cloud.github.com/assets/3270517/100501/6b41d980-6820-11e2-8f10-d6e08c87aff0.png)

I also get this nice block of errors when trying to run the rails server.

**Comment by darokel** [comment] 2013-01-29 11:01
Getting this same error. I removed the user factory which came when initialising the generator and ran rake db:migrate, rake db:seed successfully, but adding back the factory causes the error to re-occur.

**Comment by mhaagens** [comment] 2013-01-29 15:57
Yeah. I used this solution; 

The gem factory_girl_rails should be required in the spec_helper.rb rather than the gemfile - it is possible that you are requiring FactoryGirl twice which is why you are getting the duplicate.

Try this in your gem file:

group :test do
  gem "rspec"
  gem 'factory_girl_rails', :require => false
end
Then make sure that factory girl is required in the spec_helper with:

require 'factory_girl_rails'
By the way - you don't need both rspec and rpsec-rails in your gemfile. You can replace both with the following:

group :development, :test do
  gem 'rspec-rails'
end
You need rspec in both groups so that the rake tasks will work in development and the core testing will work in test.

It worked for me, but I'm just wondering if this is a problem a few are having or if it's something I'm doing wrong.

**Comment by kdiogenes** [comment] 2013-01-29 19:12
The problem is that is also a factory defined in test/factories/users.rb

**Comment by bbugh** [comment] 2013-01-29 19:18
Delete the test folder and it should work.

**Comment by mhaagens** [comment] 2013-01-29 19:19
Thanks for the help, really appreciate it! Will test in when I get a chance!

**Comment by darokel** [comment] 2013-01-30 10:55
There's always been a factory in that location when using the composer, and it worked fine a few days ago so I don't think that is the problem.

**Comment by darokel** [comment] 2013-01-30 11:03
Ahh nevermind, I just saw the new 'test' folder which is what's causing the problem in the directory. Cheers

**Comment by DanielKehoe** [comment] 2013-01-31 04:40
The issue is resolved with the newest release of rails_apps_composer (2.2.31) and the Rails Composer tool. Factory_girl_rails 4.2.0 changed default behavior for generating factories when used with RSpec. See the blog post http://j.mp/Tdqxsz and https://github.com/thoughtbot/factory_girl_rails/issues/88.

**Closed as completed by DanielKehoe** 2013-01-31 04:40 UTC
