### ISSUE TITLE
Unable to lunch app created with Rails composer

### ISSUE THREAD

**Issue by ameft** [RailsApps/rails3-bootstrap-devise-cancan#28] opened 2013-01-29 01:56 UTC
I've tried both on Windows and Ubuntu (everything up to date), getting the same error when I try to lunch the just generated application (with rails composer) with "rails s" (both Thin and Webrick):

ameft@ubuntu:~/unoscattoperlosport$ rails s
=> Booting Thin
=> Rails 3.2.11 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/decorator.rb:10:in `method_missing': Factory already registered: user (FactoryGirl::DuplicateDefinitionError)
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/decorator/disallows_duplicates_registry.rb:6:in`register'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl.rb:65:in `block in register_factory'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl.rb:64:in`each'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl.rb:64:in `register_factory'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:20:in`factory'
    from /home/ameft/unoscattoperlosport/spec/factories/users.rb:4:in `block in <top (required)>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in`instance_eval'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in `run'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:7:in`define'
    from /home/ameft/unoscattoperlosport/spec/factories/users.rb:3:in `<top (required)>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in`load'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `block in load'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:20:in`block (2 levels) in find_definitions'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:19:in `each'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:19:in`block in find_definitions'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:15:in `each'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:15:in`find_definitions'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/factory_girl_rails-4.2.0/lib/factory_girl_rails/railtie.rb:29:in `block in <class:Railtie>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:34:in`call'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:43:in`block in run_load_hooks'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:42:in `each'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:42:in`run_load_hooks'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/initializable.rb:30:in`instance_exec'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/initializable.rb:54:in`run_initializers'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /home/ameft/unoscattoperlosport/config/environment.rb:5:in `<top (required)>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in`require'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/ameft/unoscattoperlosport/config.ru:3:in`block in <main>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/builder.rb:51:in `instance_eval'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/builder.rb:51:in`initialize'
    from /home/ameft/unoscattoperlosport/config.ru:in `new'
    from /home/ameft/unoscattoperlosport/config.ru:in`<main>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/builder.rb:40:in `eval'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/builder.rb:40:in`parse_file'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/server.rb:200:in `app'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/commands/server.rb:46:in`app'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/server.rb:304:in `wrapped_app'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/rack-1.4.4/lib/rack/server.rb:254:in`start'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/commands/server.rb:70:in `start'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/commands.rb:55:in`block in <top (required)>'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/commands.rb:50:in `tap'
    from /home/ameft/.rvm/gems/ruby-1.9.3-p374@unoscattoperlosport/gems/railties-3.2.11/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by kdiogenes** [comment] 2013-01-29 19:06
The problem is that is also a factory defined in test/factories/users.rb

**Comment by darokel** [comment] 2013-01-30 10:55
@cerdiogenes There's always been a factory in that location when using the composer, and it worked fine a few days ago so I don't think that is the problem.

**Comment by darokel** [comment] 2013-01-30 11:03
Ahh nevermind, I just saw the new 'test' folder which is what's causing the problem in the directory. Cheers

**Comment by DanielKehoe** [comment] 2013-01-31 04:40
The issue is resolved with the newest release of rails_apps_composer (2.2.31) and the Rails Composer tool. Factory_girl_rails 4.2.0 changed default behavior for generating factories when used with RSpec. See the blog post http://j.mp/Tdqxsz and https://github.com/thoughtbot/factory_girl_rails/issues/88.

**Closed as completed by DanielKehoe** 2013-01-31 04:40 UTC
